[versions]
spring-boot = "4.0.3"
dependency-management = "1.1.7"
openapi-generator = "7.2.0"
checkstyle = "10.15.0"
springdoc-openapi = "3.0.1"
jackson-nullable = "0.2.6"
minio = "8.5.10"
mapstruct = "1.5.5.Final"
lombok = "1.18.30"
java = "17"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }

[libraries]
# Spring Boot
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-liquibase = { module = "org.springframework.boot:spring-boot-starter-liquibase" }
spring-boot-starter-amqp = { module = "org.springframework.boot:spring-boot-starter-amqp" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }

# Spring AMQP
spring-rabbit-stream = { module = "org.springframework.amqp:spring-rabbit-stream" }

# OpenAPI
springdoc-openapi-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }
jackson-databind-nullable = { module = "org.openapitools:jackson-databind-nullable", version.ref = "jackson-nullable" }

# Infra
minio = { module = "io.minio:minio", version.ref = "minio" }
postgresql = { module = "org.postgresql:postgresql" }

# MapStruct & Lombok
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# Test
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
spring-boot-starter-amqp-test = { module = "org.springframework.boot:spring-boot-starter-amqp-test" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }

[bundles]
spring-web = ["spring-boot-starter-web", "spring-boot-starter-webmvc", "spring-boot-starter-validation"]
spring-data = ["spring-boot-starter-data-jpa", "spring-boot-starter-liquibase"]
spring-messaging = ["spring-boot-starter-amqp", "spring-rabbit-stream"]
openapi = ["springdoc-openapi-ui", "jackson-databind-nullable"]
infra = ["minio", "postgresql"]
dev = ["spring-boot-devtools"]
test = ["junit-platform-launcher", "spring-boot-starter-amqp-test", "spring-boot-starter-data-jpa-test", "spring-boot-starter-webmvc-test"]